name: Sync GitHub Issues to ClickUp

on:
  issues:
    types: [opened, edited]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Call ClickUp API
        env:
          CLICKUP_API_TOKEN: ${{ secrets.CLICKUP_API_TOKEN }}
          CLICKUP_LIST_ID: ${{ secrets.CLICKUP_LIST_ID }}
        run: |
          # Install curl if not already installed
          sudo apt-get update && sudo apt-get install -y curl

          # Prepare ClickUp API payload
          PAYLOAD=$(cat <<EOF
          {
            "name": "GitHub Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}",
            "description": "${{ github.event.issue.body }}",
            "status": "To Do"
          }
          EOF
          )

          # Call ClickUp API to create a task
          curl -X POST "https://api.clickup.com/api/v2/list/${{ secrets.CLICKUP_LIST_ID }}/task" \
            -H "Authorization: ${{ secrets.CLICKUP_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"
